### ISSUE TITLE
 [fx54] Show compatibility warning if an add-on uses `-moz-appearance`

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/amo-validator#524]
As part of [bug 1333482](https://bugzilla.mozilla.org/show_bug.cgi?id=1333482), the valid uses of `-moz-appearance` have been limited to chrome stylesheets. Since the distinction can be subtle, all instances of `-moz-appearance` should be flagged.

This is a compatibility warning, so the add-on should still be upgraded in this case. It should also appear as a warning in regular validations.

Message:

-moz-appearance can only be used in chrome stylesheets. All other users will be ignored. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1333482) for more information.

Affected add-on: https://addons.mozilla.org/addon/dnsqueriescom-toolbar/

**Comment by wagnerand** [comment]
> All other users will be ignored.

Poor users.

I presumed you meant `uses`, so the warning will say that instead.

**Comment by Aris-t2** [comment]
Please consider to remove those compatibility warnings for legacy add-ons and only show them for WebExtensions.

Legacy add-ons will/should still be around for a year now (Fx 52.x ESR) and they can of course do far more things with "-moz-appearance", than the new "appearance:auto | none" allows (especially when add-ons are still supporting Firefox 45-53, these warnings are our of place.)

![ijvdkkp](https://cloud.githubusercontent.com/assets/6013569/25104664/832ec70e-23c1-11e7-8b0e-3a8938089a82.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=1333482#c79
https://bugzilla.mozilla.org/show_bug.cgi?id=1333482#c81

**Comment by EnTeQuAk** [comment]
It's not that easy tbh, given that your add-on supports both versions of Firefox, the one that changed `-moz-appearance` and the one that didn't it's a lot more safe to jut show the warning instead of cleverly trying to filter things out.

**Comment by Aris-t2** [comment]
I was under the impression dropping "-moz-" prefix only makes sense for WebExensions and Firefox 57+ as it clearly lacks tons of features (which won't be supported in Fx57+) when restricted to only "appearance: none" and "appearance: auto".

Even in Firefox 54 and 55 "-moz-appearance" can achieve far more than just "appearance" -->
-moz-appearance: radio
-moz-appearance: button
-moz-appearance: menuitem
etc.

![1](https://cloud.githubusercontent.com/assets/6013569/25121147/fd1a2248-2420-11e7-8e6a-83deaa97d11e.png)

**Comment by EnTeQuAk** [comment]
Reading https://www.fxsitecompat.com/en-CA/docs/2017/moz-appearance-property-has-been-removed/ it sounds like it has been generally removed? I can't tell you much about that though, maybe  @jvillalobos can shed some light here or ping the right people?

**Comment by Leif-W** [comment]
Experienced same thing as Aris has mentioned with my legacy XUL-based add-on just now, which supports Fx v29-56.  My CSS file is loaded from a chrome:// protocol.  I have top-level menus with icons, sub-menus with no icons, for which I do not want to show an empty icon column (wastes screen space).  I can use "menuitem-non-iconic" to have the text use all available space, but the browser erroneously continues to display the thin translucent vertical separator between mentuitem and the former icon.  "-moz-appearance: none" lets me remove this separator.  "appearance: none" works, but only in Fx v54-ish and newer (after the recent change from https://bugzilla.mozilla.org/show_bug.cgi?id=1333482), but not in Fx v29-54-ish.

Fx 57 may land in November-ish, but history and personal experience shows me that most users won't upgrade for anywhere from 3-5 YEARS(!), in some cases as much as 10(!!!).  I'm not here to force people to adopt sensible upgrade schedules, and some people may be stuck with draconic organizational restrictions which explicitly prohibit ad-hoc upgrades.  There may be other edge cases where people rely on a 3rd party to provide updates for platforms or other accessibility reasons which have update schedules that lag behind Mozilla.

All I'm here for is to keep an add-on functional and accessible to people if they find it useful.  So some legacy support is still desirable, so that I can at least fix the add-on. i.e. if the 3rd party sites it relies upon changes/breaks, or bugs are discovered.

As far as validation reports, is there any way this could be bumped down from /!\ Warning to (i) Notice?  If it is non-actionable false positive on perfectly valid code given the browser version and type of add-on, merely intended to convey information about an recent soft-change (for my use case XUL) and upcoming hard-change (for WebExtensions), I think an information notice is more appropriate than a warning.  Even in the case of WebExtensions, some add-ons have been converted for as much as a year now, and so they may wish to still support 1 years worth of browsers before this change for which "appearance" may not work at all.  This creates a problematic gap in range of long-term support.

A validator/test which ignores the type of add-on when there are 3-5 possibilities (depending whether you consider XUL/restartless/bootstrap to be effectively the same thing, SDK and WebExt), and also ignores the min and max versions intended to be supported, is a poorly designed validator/test, and the excuse being that trying to be clever is unsafe or too difficult, is an invalid excuse.  A validator which does not clearly communicate if a piece of code is valid or not, is not functioning properly.  It is not our fault as add-on developers that Mozilla decided to spew out an entirely new add-on API every couple years for the past decade, and we should not be blamed or dismissed for trying to support our users, who may only use the Mozilla browser for the add-on(s).

**Comment by jvillalobos** [comment]
According to bug 1333482, `-moz-appearance` only works in CSS sheets loaded from `chrome` URLs. This isn't exclusive to WebExtensions. It's true that most uses in legacy add-ons should be okay, but refining the test to reduce the false positives is probably more work than it's worth.

Since the bulk validation for 54 was already run, this test has already accomplished its main purpose. It sounds like it adds too much noise, so we could disable it now. @wagnerand, what do you think?

**Comment by wagnerand** [comment]
This wouldn't be the first warning that adds some noise. While I don't have a super strong feeling, I'd lean towards keeping it since imho a false positive is still better than surprised developers because we didn't tell them about changed behavior.

**Comment by Aris-t2** [comment]
@wagnerand
Would it be possible to add another check for application min version?
For example, if an add-on uses "-moz-appearance" and only supports Fx54+, show warning.
If an add-on supports anything Fx29-56, do not show warning.

**Comment by wagnerand** [comment]
I'm not sure how easy that would be. We are also focusing on WebExtensions now, so amo-validator is on life-support. That being said, I think we'd accept a patch for it.
